# Generated by Django 6.0.3 on 2026-04-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drug_catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clinicproductmapping",
            new_name="drug_catalo_clinic__26a300_idx",
            old_name="drug_catalog_clinic__f4e1a2_idx",
        ),
        migrations.RenameIndex(
            model_name="referenceproduct",
            new_name="drug_catalo_name_8351ec_idx",
            old_name="drug_catalog_name_0c0c9c_idx",
        ),
        migrations.RenameIndex(
            model_name="referenceproduct",
            new_name="drug_catalo_externa_5d2762_idx",
            old_name="drug_catalog_externa_7f3b2c_idx",
        ),
    ]
