# Generated by Django 6.0 on 2025-12-23 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("tenancy", "0002_clinicholiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["name", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_clinic__93101f_idx",
        ),
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="min_stock_level",
            new_name="low_stock_threshold",
        ),
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="stock_quantity",
            new_name="stock_on_hand",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_inventory_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(default="pcs", max_length=32),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["clinic", "name"], name="inventory_i_clinic__32da91_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["clinic", "sku"], name="inventory_i_clinic__1a8d84_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["clinic", "is_active"], name="inventory_i_clinic__4bf79f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("clinic", "sku"),
                name="uniq_inventoryitem_clinic_sku",
            ),
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="description",
        ),
    ]
