# Generated by Django 6.0 on 2025-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventoryitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("medication", "Medication"),
                    ("supply", "Supply"),
                    ("food", "Food"),
                    ("other", "Other"),
                ],
                default="supply",
                max_length=20,
            ),
        ),
    ]
