# Generated by Django 6.0 on 2025-12-23 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventoryitem_category"),
        ("tenancy", "0002_clinicholiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjust", "Adjustment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("patient_id", models.IntegerField(blank=True, null=True)),
                ("appointment_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="inventoryitem",
            name="uniq_inventoryitem_clinic_sku",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_clinic__4bf79f_idx",
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("medication", "Medication"),
                    ("supply", "Supplies"),
                    ("food", "Food"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="low_stock_threshold",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="stock_on_hand",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["clinic", "category"], name="inventory_i_clinic__93101f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["clinic", "stock_on_hand"], name="inventory_i_clinic__5fac71_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("clinic", "sku"), name="uniq_inventory_sku_per_clinic"
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_movements",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_inventory_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="price_cents",
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["clinic", "created_at"], name="inventory_i_clinic__567213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["item", "created_at"], name="inventory_i_item_id_8deff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["clinic", "item", "created_at"], name="inventory_i_clinic__e35ab8_idx"
            ),
        ),
    ]
