"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from .caches import get_caches_config
from .rq import build_rq_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (in project root, one level up from backend/)
# Try both backend/.env and project root .env
env_path = BASE_DIR.parent / ".env"
if not env_path.exists():
    env_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path, override=True)


def _env_bool(key: str, default: bool) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


def _split_csv(name: str) -> list[str]:
    raw = os.getenv(name, "").strip()
    return [x.strip() for x in raw.split(",") if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Dev: omit DJANGO_DEBUG or set 1/true. Prod: DJANGO_DEBUG=0 and DJANGO_SECRET_KEY set.
DEBUG = _env_bool("DJANGO_DEBUG", True)

_DEV_INSECURE_SECRET_KEY = "django-insecure-!xlvc@w2#_0bajgy^wd)56y6xj_l8@(kmknbc_t0qy03-6*z1&"
SECRET_KEY = (os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY") or "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = _DEV_INSECURE_SECRET_KEY
    else:
        raise ImproperlyConfigured(
            "Set DJANGO_SECRET_KEY (or SECRET_KEY) when DJANGO_DEBUG is false."
        )

_allowed = _split_csv("ALLOWED_HOSTS")
if _allowed:
    ALLOWED_HOSTS = _allowed
elif DEBUG:
    # runserver + docker service name used by compose healthchecks / internal calls
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "backend"]
else:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must be set when DJANGO_DEBUG is false (comma-separated hostnames)."
    )


# Application definition
INSTALLED_APPS = [
    "config.apps.ConfigConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "django_rq",
    # Local apps
    "apps.tenancy.apps.TenancyConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.clients.apps.ClientsConfig",
    "apps.patients.apps.PatientsConfig",
    "apps.scheduling.apps.SchedulingConfig",
    "apps.inventory.apps.InventoryConfig",
    "apps.medical.apps.MedicalConfig",
    "apps.drug_catalog.apps.DrugCatalogConfig",
    "apps.billing.apps.BillingConfig",
    "apps.labs.apps.LabsConfig",
    "apps.reminders.apps.RemindersConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.documents.apps.DocumentsConfig",
    "apps.consents.apps.ConsentsConfig",
    "apps.audit.apps.AuditConfig",
    "apps.reports.apps.ReportsConfig",
    "apps.portal.apps.PortalConfig",
    "apps.webhooks.apps.WebhooksConfig",
    "apps.inbox.apps.InboxConfig",
    "apps.device_management.apps.DeviceManagementConfig",
    "behave_django",
]

AUTH_USER_MODEL = "accounts.User"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # MUSI BYĆ NA GÓRZE
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "config.middleware.RequestContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cache (portal OTP / confirm rate limits; Redis when REDIS_URL is set — see config/caches.py)
CACHES = get_caches_config()

# Redis Queue (async workers); see documentation/ASYNC_JOB_QUEUE.md
RQ_QUEUES, RQ_REPORT_EXPORT_ENQUEUE = build_rq_config()

# Outbound integration webhooks — see documentation/INTEGRATION_WEBHOOKS.md
WEBHOOK_DELIVERY_USE_THREAD = _env_bool("WEBHOOK_DELIVERY_USE_THREAD", True)

# Superuser / network_admin clinic-id lists (see apps.tenancy.access); invalidated when Clinic rows change.
ACCESSIBLE_CLINIC_IDS_CACHE_TIMEOUT = int(
    (os.getenv("ACCESSIBLE_CLINIC_IDS_CACHE_TIMEOUT") or "300").strip() or "300"
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

_default_cors_origins = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:5173",
    "http://localhost:5174",
]
_cors_from_env = _split_csv("CORS_ALLOWED_ORIGINS")
if _cors_from_env:
    CORS_ALLOWED_ORIGINS = _cors_from_env
elif DEBUG:
    CORS_ALLOWED_ORIGINS = _default_cors_origins
else:
    CORS_ALLOWED_ORIGINS = []

_csrf_from_env = _split_csv("CSRF_TRUSTED_ORIGINS")
if _csrf_from_env:
    CSRF_TRUSTED_ORIGINS = _csrf_from_env
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = list(_default_cors_origins)
else:
    CSRF_TRUSTED_ORIGINS = []
_throttle_anon = os.getenv("API_THROTTLE_ANON", "120/hour")
_throttle_user = os.getenv("API_THROTTLE_USER", "5000/hour")
_throttle_transcribe = os.getenv("API_THROTTLE_TRANSCRIBE", "40/hour")
_throttle_recording = os.getenv("API_THROTTLE_RECORDING_UPLOAD", "80/hour")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.portal.authentication.PortalJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "config.exception_handler.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": _throttle_anon,
        "user": _throttle_user,
        "visit_transcribe": _throttle_transcribe,
        "visit_recording_upload": _throttle_recording,
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "VETO API",
    "DESCRIPTION": "Veterinary clinic management REST API (staff JWT + client portal).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
}
if DEBUG:
    SPECTACULAR_SETTINGS["SERVE_PERMISSIONS"] = ["rest_framework.permissions.AllowAny"]
else:
    SPECTACULAR_SETTINGS["SERVE_PERMISSIONS"] = ["rest_framework.permissions.IsAuthenticated"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "config.logging_filters.RequestContextFilter",
        }
    },
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s request_id=%(request_id)s user_id=%(user_id)s clinic_id=%(clinic_id)s %(message)s"
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_context"],
            "formatter": "default",
        }
    },
    "root": {"handlers": ["console"], "level": os.getenv("LOG_LEVEL", "INFO")},
}

# OpenAI API Key (optional - can be set via environment variable)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
}

# Client booking portal (OTP + short-lived portal JWT; not staff SimpleJWT)
PORTAL_OTP_EXPIRE_MINUTES = int(os.getenv("PORTAL_OTP_EXPIRE_MINUTES", "15"))
PORTAL_ACCESS_TOKEN_LIFETIME = timedelta(hours=int(os.getenv("PORTAL_ACCESS_TOKEN_HOURS", "24")))
# SECURITY: never enable in production — only for local dev / tests
PORTAL_RETURN_OTP_IN_RESPONSE = os.getenv("PORTAL_RETURN_OTP_IN_RESPONSE", "").lower() in (
    "1",
    "true",
    "yes",
)
# Send portal login OTP via SendGrid (uses REMINDER_SENDGRID_* API key / from-address)
PORTAL_OTP_EMAIL_ENABLED = os.getenv("PORTAL_OTP_EMAIL_ENABLED", "").lower() in (
    "1",
    "true",
    "yes",
)
# Rate limits (django.core.cache counters; 429 when exceeded)
PORTAL_OTP_REQUEST_LIMIT_PER_IP = int(os.getenv("PORTAL_OTP_REQUEST_LIMIT_PER_IP", "60"))
PORTAL_OTP_REQUEST_IP_WINDOW_SEC = int(os.getenv("PORTAL_OTP_REQUEST_IP_WINDOW_SEC", "3600"))
PORTAL_OTP_REQUEST_LIMIT_PER_MAILBOX = int(os.getenv("PORTAL_OTP_REQUEST_LIMIT_PER_MAILBOX", "10"))
PORTAL_OTP_REQUEST_MAILBOX_WINDOW_SEC = int(
    os.getenv("PORTAL_OTP_REQUEST_MAILBOX_WINDOW_SEC", "900")
)
PORTAL_OTP_CONFIRM_LIMIT_PER_IP = int(os.getenv("PORTAL_OTP_CONFIRM_LIMIT_PER_IP", "80"))
PORTAL_OTP_CONFIRM_IP_WINDOW_SEC = int(os.getenv("PORTAL_OTP_CONFIRM_IP_WINDOW_SEC", "900"))
PORTAL_OTP_CONFIRM_LIMIT_PER_MAILBOX = int(os.getenv("PORTAL_OTP_CONFIRM_LIMIT_PER_MAILBOX", "30"))
PORTAL_OTP_CONFIRM_MAILBOX_WINDOW_SEC = int(
    os.getenv("PORTAL_OTP_CONFIRM_MAILBOX_WINDOW_SEC", "900")
)
# POST /api/portal/auth/magic-link/ (one-time token from email)
PORTAL_MAGIC_LINK_LIMIT_PER_IP = int(os.getenv("PORTAL_MAGIC_LINK_LIMIT_PER_IP", "60"))
PORTAL_MAGIC_LINK_IP_WINDOW_SEC = int(os.getenv("PORTAL_MAGIC_LINK_IP_WINDOW_SEC", "900"))
# Optional: "https://app.example/booking?portal_token={token}" — {token} replaced with secret
PORTAL_MAGIC_LINK_URL_TEMPLATE = os.getenv("PORTAL_MAGIC_LINK_URL_TEMPLATE", "").strip()
# Dev/staging: allow POST .../complete-deposit/ with {"simulated": true}
PORTAL_ALLOW_SIMULATED_PAYMENT = os.getenv("PORTAL_ALLOW_SIMULATED_PAYMENT", "").lower() in (
    "1",
    "true",
    "yes",
)
PORTAL_NOTIFY_STAFF_ON_BOOKING = os.getenv("PORTAL_NOTIFY_STAFF_ON_BOOKING", "1").lower() in (
    "1",
    "true",
    "yes",
)
PORTAL_CONFIRM_FAIL_LIMIT_MAILBOX = int(os.getenv("PORTAL_CONFIRM_FAIL_LIMIT_MAILBOX", "10"))
PORTAL_CONFIRM_FAIL_WINDOW_SEC = int(os.getenv("PORTAL_CONFIRM_FAIL_WINDOW_SEC", "900"))
PORTAL_CONFIRM_LOCKOUT_SEC = int(os.getenv("PORTAL_CONFIRM_LOCKOUT_SEC", "900"))
PORTAL_CONFIRM_FAIL_LIMIT_IP = int(os.getenv("PORTAL_CONFIRM_FAIL_LIMIT_IP", "40"))
PORTAL_CONFIRM_FAIL_IP_WINDOW_SEC = int(os.getenv("PORTAL_CONFIRM_FAIL_IP_WINDOW_SEC", "900"))
PORTAL_CONFIRM_LOCKOUT_IP_SEC = int(os.getenv("PORTAL_CONFIRM_LOCKOUT_IP_SEC", "1800"))

# Stripe (portal booking deposit — Checkout Session + webhook)
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "").strip()

# Hospitalization workflow feature flags
# If True: block /discharge/ when safety checks have blocking reasons.
REQUIRE_DISCHARGE_SAFETY_FOR_DISCHARGE = False

REMINDER_EMAIL_PROVIDER = os.getenv("REMINDER_EMAIL_PROVIDER", "internal")
REMINDER_SMS_PROVIDER = os.getenv("REMINDER_SMS_PROVIDER", "internal")
REMINDER_WEBHOOK_TOKEN = os.getenv("REMINDER_WEBHOOK_TOKEN", "")
REMINDER_SENDGRID_API_KEY = os.getenv("REMINDER_SENDGRID_API_KEY", "")
REMINDER_SENDGRID_FROM_EMAIL = os.getenv("REMINDER_SENDGRID_FROM_EMAIL", "")
REMINDER_SENDGRID_FROM_NAME = os.getenv("REMINDER_SENDGRID_FROM_NAME", "Veto Clinic")
REMINDER_SENDGRID_WEBHOOK_SECRET = os.getenv("REMINDER_SENDGRID_WEBHOOK_SECRET", "")
REMINDER_TWILIO_ACCOUNT_SID = os.getenv("REMINDER_TWILIO_ACCOUNT_SID", "")
REMINDER_TWILIO_AUTH_TOKEN = os.getenv("REMINDER_TWILIO_AUTH_TOKEN", "")
REMINDER_TWILIO_FROM_NUMBER = os.getenv("REMINDER_TWILIO_FROM_NUMBER", "")
REMINDER_TWILIO_STATUS_CALLBACK_URL = os.getenv("REMINDER_TWILIO_STATUS_CALLBACK_URL", "")
REMINDER_TWILIO_WEBHOOK_SECRET = os.getenv("REMINDER_TWILIO_WEBHOOK_SECRET", "")
REMINDER_PORTAL_BASE_URL = os.getenv("REMINDER_PORTAL_BASE_URL", "")
REMINDER_PORTAL_TOKEN_TTL_HOURS = int(os.getenv("REMINDER_PORTAL_TOKEN_TTL_HOURS", "72"))

# Availability defaults (MVP)
# REMEMBER
# TODO
DEFAULT_CLINIC_OPEN_TIME = "09:00"
DEFAULT_CLINIC_CLOSE_TIME = "17:00"
DEFAULT_SLOT_MINUTES = 30

# Document ingestion pipeline (single bucket for I/O)
DOCUMENTS_DATA_S3_BUCKET = os.getenv("DOCUMENTS_DATA_S3_BUCKET", "")
DOCUMENTS_S3_REGION = os.getenv("DOCUMENTS_S3_REGION", "us-east-1")
DOCUMENTS_MAX_UPLOAD_MB = int(os.getenv("DOCUMENTS_MAX_UPLOAD_MB", "50"))

# Lab instrument ingest — raw payloads on S3 (see documentation/LAB_INTEGRATION.md)
# LAB_INGESTION_S3_ENABLED: set false if you share a prod-like .env locally but do not want lab blobs on S3.
_LAB_INGEST_S3_EN = os.getenv("LAB_INGESTION_S3_ENABLED", "true").strip().lower()
LAB_INGESTION_S3_ENABLED = _LAB_INGEST_S3_EN not in ("0", "false", "no", "off")
# Bucket: LAB_INGESTION_S3_BUCKET, or when empty fallback to DOCUMENTS_DATA_S3_BUCKET.
# Mode: auto (large payloads to S3), always, never.
LAB_INGESTION_S3_PREFIX = os.getenv("LAB_INGESTION_S3_PREFIX", "lab-ingestion").strip().strip("/")
LAB_INGESTION_S3_BUCKET = os.getenv("LAB_INGESTION_S3_BUCKET", "").strip()
LAB_INGESTION_S3_REGION = os.getenv("LAB_INGESTION_S3_REGION", "").strip() or DOCUMENTS_S3_REGION
LAB_INGESTION_RAW_INLINE_MAX_BYTES = int(
    os.getenv("LAB_INGESTION_RAW_INLINE_MAX_BYTES", str(512 * 1024))
)
LAB_INGESTION_S3_MODE = os.getenv("LAB_INGESTION_S3_MODE", "auto").strip().lower()

# Visit recording + AI summary pipeline
VISIT_RECORDINGS_S3_BUCKET = os.getenv("VISIT_RECORDINGS_S3_BUCKET", "")
VISIT_RECORDINGS_S3_REGION = os.getenv("VISIT_RECORDINGS_S3_REGION", DOCUMENTS_S3_REGION)
VISIT_RECORDINGS_MAX_UPLOAD_MB = int(os.getenv("VISIT_RECORDINGS_MAX_UPLOAD_MB", "200"))
VISIT_RECORDINGS_PROCESS_INLINE_ON_UPLOAD = (
    os.getenv("VISIT_RECORDINGS_PROCESS_INLINE_ON_UPLOAD", "true").lower() == "true"
    if DEBUG
    else os.getenv("VISIT_RECORDINGS_PROCESS_INLINE_ON_UPLOAD", "false").lower() == "true"
)

# Direct visit audio → clinical exam transcription (Whisper + structuring)
VISIT_TRANSCRIPTION_INLINE_PROCESSING = (
    os.getenv("VISIT_TRANSCRIPTION_INLINE_PROCESSING", "true").lower() == "true"
    if DEBUG
    else os.getenv("VISIT_TRANSCRIPTION_INLINE_PROCESSING", "false").lower() == "true"
)

# Self-hosted Whisper transcription service
WHISPER_SERVICE_URL = os.getenv("WHISPER_SERVICE_URL", "http://localhost:9000")
