"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (in project root, one level up from backend/)
# Try both backend/.env and project root .env
env_path = BASE_DIR.parent / ".env"
if not env_path.exists():
    env_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!xlvc@w2#_0bajgy^wd)56y6xj_l8@(kmknbc_t0qy03-6*z1&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_allowed = os.getenv("ALLOWED_HOSTS")
ALLOWED_HOSTS = [x.strip() for x in _allowed.split(",") if x.strip()] if _allowed else []


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    # Local apps
    "apps.tenancy.apps.TenancyConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.clients.apps.ClientsConfig",
    "apps.patients.apps.PatientsConfig",
    "apps.scheduling.apps.SchedulingConfig",
    "apps.inventory.apps.InventoryConfig",
    "apps.medical.apps.MedicalConfig",
    "apps.billing.apps.BillingConfig",
    "apps.labs.apps.LabsConfig",
    "apps.reminders.apps.RemindersConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.documents.apps.DocumentsConfig",
    "apps.audit.apps.AuditConfig",
    "apps.reports.apps.ReportsConfig",
    "apps.portal.apps.PortalConfig",
]

AUTH_USER_MODEL = "accounts.User"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # MUSI BYĆ NA GÓRZE
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "config.middleware.RequestContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:5173",
    "http://localhost:5174",
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.portal.authentication.PortalJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "config.exception_handler.custom_exception_handler",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "config.logging_filters.RequestContextFilter",
        }
    },
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s request_id=%(request_id)s user_id=%(user_id)s clinic_id=%(clinic_id)s %(message)s"
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_context"],
            "formatter": "default",
        }
    },
    "root": {"handlers": ["console"], "level": os.getenv("LOG_LEVEL", "INFO")},
}

# OpenAI API Key (optional - can be set via environment variable)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
}

# Client booking portal (OTP + short-lived portal JWT; not staff SimpleJWT)
PORTAL_OTP_EXPIRE_MINUTES = int(os.getenv("PORTAL_OTP_EXPIRE_MINUTES", "15"))
PORTAL_ACCESS_TOKEN_LIFETIME = timedelta(hours=int(os.getenv("PORTAL_ACCESS_TOKEN_HOURS", "24")))
# SECURITY: never enable in production — only for local dev / tests
PORTAL_RETURN_OTP_IN_RESPONSE = os.getenv("PORTAL_RETURN_OTP_IN_RESPONSE", "").lower() in (
    "1",
    "true",
    "yes",
)
# Dev/staging: allow POST .../complete-deposit/ with {"simulated": true}
PORTAL_ALLOW_SIMULATED_PAYMENT = os.getenv("PORTAL_ALLOW_SIMULATED_PAYMENT", "").lower() in (
    "1",
    "true",
    "yes",
)

# Stripe (portal booking deposit — Checkout Session + webhook)
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "").strip()

# Hospitalization workflow feature flags
# If True: block /discharge/ when safety checks have blocking reasons.
REQUIRE_DISCHARGE_SAFETY_FOR_DISCHARGE = False

REMINDER_EMAIL_PROVIDER = os.getenv("REMINDER_EMAIL_PROVIDER", "internal")
REMINDER_SMS_PROVIDER = os.getenv("REMINDER_SMS_PROVIDER", "internal")
REMINDER_WEBHOOK_TOKEN = os.getenv("REMINDER_WEBHOOK_TOKEN", "")
REMINDER_SENDGRID_API_KEY = os.getenv("REMINDER_SENDGRID_API_KEY", "")
REMINDER_SENDGRID_FROM_EMAIL = os.getenv("REMINDER_SENDGRID_FROM_EMAIL", "")
REMINDER_SENDGRID_FROM_NAME = os.getenv("REMINDER_SENDGRID_FROM_NAME", "Veto Clinic")
REMINDER_SENDGRID_WEBHOOK_SECRET = os.getenv("REMINDER_SENDGRID_WEBHOOK_SECRET", "")
REMINDER_TWILIO_ACCOUNT_SID = os.getenv("REMINDER_TWILIO_ACCOUNT_SID", "")
REMINDER_TWILIO_AUTH_TOKEN = os.getenv("REMINDER_TWILIO_AUTH_TOKEN", "")
REMINDER_TWILIO_FROM_NUMBER = os.getenv("REMINDER_TWILIO_FROM_NUMBER", "")
REMINDER_TWILIO_STATUS_CALLBACK_URL = os.getenv("REMINDER_TWILIO_STATUS_CALLBACK_URL", "")
REMINDER_TWILIO_WEBHOOK_SECRET = os.getenv("REMINDER_TWILIO_WEBHOOK_SECRET", "")
REMINDER_PORTAL_BASE_URL = os.getenv("REMINDER_PORTAL_BASE_URL", "")
REMINDER_PORTAL_TOKEN_TTL_HOURS = int(os.getenv("REMINDER_PORTAL_TOKEN_TTL_HOURS", "72"))

# Availability defaults (MVP)
# REMEMBER
# TODO
DEFAULT_CLINIC_OPEN_TIME = "09:00"
DEFAULT_CLINIC_CLOSE_TIME = "17:00"
DEFAULT_SLOT_MINUTES = 30

# Document ingestion pipeline (single bucket for I/O)
DOCUMENTS_DATA_S3_BUCKET = os.getenv("DOCUMENTS_DATA_S3_BUCKET", "")
DOCUMENTS_S3_REGION = os.getenv("DOCUMENTS_S3_REGION", "us-east-1")
DOCUMENTS_MAX_UPLOAD_MB = int(os.getenv("DOCUMENTS_MAX_UPLOAD_MB", "50"))

# Visit recording + AI summary pipeline
VISIT_RECORDINGS_S3_BUCKET = os.getenv("VISIT_RECORDINGS_S3_BUCKET", "")
VISIT_RECORDINGS_S3_REGION = os.getenv("VISIT_RECORDINGS_S3_REGION", DOCUMENTS_S3_REGION)
VISIT_RECORDINGS_MAX_UPLOAD_MB = int(os.getenv("VISIT_RECORDINGS_MAX_UPLOAD_MB", "200"))
VISIT_RECORDINGS_PROCESS_INLINE_ON_UPLOAD = (
    os.getenv("VISIT_RECORDINGS_PROCESS_INLINE_ON_UPLOAD", "true").lower() == "true"
    if DEBUG
    else os.getenv("VISIT_RECORDINGS_PROCESS_INLINE_ON_UPLOAD", "false").lower() == "true"
)
