# Generated by Django 6.0 on 2026-03-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_nip"),
        ("reminders", "0001_initial"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="last_webhook_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reminder",
            name="provider",
            field=models.CharField(
                choices=[("internal", "Internal"), ("sendgrid", "SendGrid"), ("twilio", "Twilio")],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reminder",
            name="provider_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("deferred", "Deferred"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ReminderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("enqueued", "Enqueued"),
                            ("deferred", "Deferred"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("webhook_update", "Webhook update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="reminders.reminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["reminder", "event_type"], name="reminders_r_reminde_37a5e3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReminderPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("allow_email", models.BooleanField(default=True)),
                ("allow_sms", models.BooleanField(default=False)),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("auto", "Auto"), ("email", "Email"), ("sms", "SMS")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_preferences",
                        to="clients.client",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_preferences",
                        to="tenancy.clinic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["clinic", "client"], name="reminders_r_clinic__128d0a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "client"), name="reminders_pref_clinic_client_uniq"
                    )
                ],
            },
        ),
    ]
