# Generated by Django 6.0.2 on 2026-03-14 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0002_reminder_delivered_at_reminder_last_webhook_payload_and_more"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderpreference",
            name="locale",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("vaccination", "Vaccination"),
                            ("invoice", "Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=10),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("en", "English"), ("pl", "Polski")], default="en", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("subject_template", models.CharField(blank=True, max_length=255)),
                ("body_template", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_templates",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_reminder_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReminderTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("subject_template", models.CharField(blank=True, max_length=255)),
                ("body_template", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="reminders.remindertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="remindertemplate",
            index=models.Index(
                fields=["clinic", "reminder_type", "channel", "locale", "is_active"],
                name="reminders_r_clinic__2ad6e6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="remindertemplate",
            constraint=models.UniqueConstraint(
                fields=("clinic", "reminder_type", "channel", "locale"),
                name="reminders_template_clinic_type_channel_locale_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="remindertemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="reminders_template_version_uniq"
            ),
        ),
    ]
