# Generated by Django 6.0.2 on 2026-03-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0003_reminderpreference_locale_remindertemplate_and_more"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_provider",
                    models.CharField(
                        choices=[("internal", "Internal"), ("sendgrid", "SendGrid")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "sms_provider",
                    models.CharField(
                        choices=[("internal", "Internal"), ("twilio", "Twilio")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_provider_config",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_reminder_provider_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["clinic", "email_provider", "sms_provider"],
                        name="reminders_r_clinic__c9b1bb_idx",
                    )
                ],
            },
        ),
    ]
