# Generated by Django 6.0.2 on 2026-03-16 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0006_reminderinboundreply_alter_reminderevent_event_type"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderPortalActionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("confirm", "Confirm"),
                            ("cancel", "Cancel"),
                            ("reschedule_request", "Reschedule request"),
                        ],
                        max_length=24,
                    ),
                ),
                ("token_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_portal_tokens",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_tokens",
                        to="reminders.reminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "action", "expires_at"],
                        name="reminders_r_clinic__403060_idx",
                    ),
                    models.Index(
                        fields=["reminder", "action"], name="reminders_r_reminde_18d8c5_idx"
                    ),
                ],
            },
        ),
    ]
