# Generated by Django 6.0.2 on 2026-03-16 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0007_reminderportalactiontoken"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminderevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("enqueued", "Enqueued"),
                    ("deferred", "Deferred"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("webhook_update", "Webhook update"),
                    ("reply_received", "Reply received"),
                    ("escalated", "Escalated"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReminderEscalationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("appointment_unconfirmed", "Appointment unconfirmed"),
                            ("reschedule_unresolved", "Reschedule unresolved"),
                            ("invoice_overdue", "Invoice overdue"),
                        ],
                        max_length=40,
                    ),
                ),
                ("delay_minutes", models.PositiveIntegerField(default=60)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("enqueue_followup", "Enqueue follow-up reminder"),
                            ("flag_for_review", "Flag unresolved for review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_executions_per_target", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_escalation_rules",
                        to="tenancy.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["clinic_id", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReminderEscalationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_key", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("skipped", "Skipped")],
                        default="applied",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_escalation_executions",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_executions",
                        to="reminders.reminder",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reminders.reminderescalationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="reminderescalationrule",
            index=models.Index(
                fields=["clinic", "is_active", "trigger_type"],
                name="reminders_r_clinic__5846b6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderescalationrule",
            constraint=models.UniqueConstraint(
                fields=("clinic", "name"), name="reminders_escalation_rule_clinic_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="reminderescalationexecution",
            index=models.Index(
                fields=["clinic", "created_at"], name="reminders_r_clinic__1efabe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminderescalationexecution",
            index=models.Index(
                fields=["rule", "target_key"], name="reminders_r_rule_id_7c278c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderescalationexecution",
            constraint=models.UniqueConstraint(
                fields=("rule", "reminder"), name="reminders_escalation_rule_reminder_uniq"
            ),
        ),
    ]
