# Generated by Django 6.0.2 on 2026-03-17 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_clinic_nip_ksef_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("appointment_confirmed", "Appointment confirmed"),
                            ("reschedule_request", "Reschedule request"),
                            ("escalation_triggered", "Escalation triggered"),
                            ("invoice_overdue", "Invoice overdue"),
                            ("low_stock", "Low stock"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(max_length=500)),
                ("link_tab", models.CharField(blank=True, max_length=64)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    ),
                    models.Index(
                        fields=["clinic", "kind", "created_at"],
                        name="notificatio_clinic__7fe616_idx",
                    ),
                ],
            },
        ),
    ]
