# Generated by Django 6.0.3 on 2026-03-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("appointment_confirmed", "Appointment confirmed"),
                    ("reschedule_request", "Reschedule request"),
                    ("escalation_triggered", "Escalation triggered"),
                    ("invoice_overdue", "Invoice overdue"),
                    ("low_stock", "Low stock"),
                    ("portal_appointment_booked", "Online booking (portal)"),
                ],
                max_length=40,
            ),
        ),
    ]
