# Generated by Django 6.0.3 on 2026-04-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_clinic_portal_booking_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="reminder_sms_enabled",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, queued SMS reminders are cancelled during processing (email is unaffected).",
            ),
        ),
    ]
