# Generated by Django 6.0 on 2025-12-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_patienthistoryentry"),
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0003_vetavailabilityexception"),
        ("tenancy", "0002_clinicholiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("initial_notes", models.TextField(blank=True)),
                ("clinical_examination", models.TextField(blank=True)),
                (
                    "temperature_c",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("heart_rate_bpm", models.PositiveIntegerField(blank=True, null=True)),
                ("respiratory_rate_rpm", models.PositiveIntegerField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True)),
                ("owner_instructions", models.TextField(blank=True)),
                ("initial_diagnosis", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="patienthistoryentry",
            name="medical_pat_clinic__39ee0e_idx",
        ),
        migrations.RemoveIndex(
            model_name="patienthistoryentry",
            name="medical_pat_clinic__ce90d9_idx",
        ),
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="assessment",
            new_name="ai_summary",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="objective",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="subjective",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="temperature_c",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="weight_kg",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="clinic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medical_records",
                related_query_name="medical_record",
                to="tenancy.clinic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="patients.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patienthistoryentry",
            name="record",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_entries",
                to="medical.medicalrecord",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_medical_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patienthistoryentry",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_history_entries",
                related_query_name="patient_history_entry",
                to="tenancy.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="patienthistoryentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_patient_history_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patienthistoryentry",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(fields=["clinic", "patient"], name="medical_med_clinic__1b3095_idx"),
        ),
        migrations.AddIndex(
            model_name="patienthistoryentry",
            index=models.Index(
                fields=["clinic", "record", "-created_at"], name="medical_pat_clinic__7fe3a4_idx"
            ),
        ),
        migrations.AddField(
            model_name="clinicalexam",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinical_exam",
                to="scheduling.appointment",
            ),
        ),
        migrations.AddField(
            model_name="clinicalexam",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_exams",
                related_query_name="clinical_exam",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="clinicalexam",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_clinical_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="patienthistoryentry",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="patienthistoryentry",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patienthistoryentry",
            name="receipt_summary",
        ),
        migrations.AddIndex(
            model_name="clinicalexam",
            index=models.Index(
                fields=["clinic", "appointment"], name="medical_cli_clinic__b43313_idx"
            ),
        ),
    ]
