# Generated by Django 6.0.2 on 2026-03-17 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_ksef_fields"),
        ("medical", "0007_prescription_drug_fields"),
        ("scheduling", "0009_remove_time_from_working_hours_unique"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patienthistoryentry",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_history_entries",
                to="scheduling.appointment",
            ),
        ),
        migrations.AddField(
            model_name="patienthistoryentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_history_entries",
                to="billing.invoice",
            ),
        ),
        migrations.AddIndex(
            model_name="patienthistoryentry",
            index=models.Index(
                fields=["clinic", "appointment", "-created_at"],
                name="medical_pat_clinic__582ac9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patienthistoryentry",
            index=models.Index(
                fields=["clinic", "invoice", "-created_at"], name="medical_pat_clinic__9bce12_idx"
            ),
        ),
    ]
