# Generated by Django 6.0.2 on 2026-03-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0008_patienthistoryentry_appointment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalexam",
            name="ai_notes_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="clinicalexam",
            name="transcript",
            field=models.TextField(blank=True),
        ),
    ]
