# Generated by Django 6.0.2 on 2026-03-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0009_clinicalexam_ai_notes_raw_clinicalexam_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalexam",
            name="weight_kg",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
