# Generated by Django 6.0.3 on 2026-04-02 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_is_active_back_to_inventoryitem"),
        ("medical", "0011_clinicalexamtemplate"),
        ("tenancy", "0005_clinic_portal_booking_deposit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureSupplyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("visit_type", models.CharField(blank=True, default="", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_supply_templates",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_procedure_supply_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureSupplyTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "suggested_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "default_unit_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        choices=[
                            ("23", "23%"),
                            ("8", "8%"),
                            ("5", "5%"),
                            ("0", "0%"),
                            ("zw", "Zwolniony (zw)"),
                            ("oo", "Odwrotne obciążenie (oo)"),
                            ("np", "Poza VAT (np)"),
                        ],
                        default="8",
                        max_length=4,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_supply_template_lines",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="medical.proceduresupplytemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="proceduresupplytemplate",
            index=models.Index(fields=["clinic", "is_active"], name="medical_ps_tpl_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="proceduresupplytemplate",
            constraint=models.UniqueConstraint(
                fields=("clinic", "name"), name="medical_proc_supply_tpl_name_uniq"
            ),
        ),
    ]
