# Generated by Django 6.0.3 on 2026-04-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0013_prescription_reference_product"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clinicalexamtemplate",
            name="medical_clinical_exam_template_name_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="proceduresupplytemplate",
            name="medical_proc_supply_tpl_name_uniq",
        ),
        migrations.AddConstraint(
            model_name="clinicalexamtemplate",
            constraint=models.UniqueConstraint(
                fields=("clinic", "name"), name="medical_ce_tmpl_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="proceduresupplytemplate",
            constraint=models.UniqueConstraint(
                fields=("clinic", "name"), name="medical_ps_tpl_name_uniq"
            ),
        ),
    ]
