# Generated by Django 6.0.3 on 2026-04-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consents", "0001_initial_consent_document"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="consentdocument",
            new_name="consents_co_clinic__63c21c_idx",
            old_name="consents_doc_clinic_appt",
        ),
    ]
