# Generated by Django 6.0 on 2026-03-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="service",
            table="billing_service",
        ),
    ]
