# Generated by Django 6.0 on 2025-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="ai_summary_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
