# Generated by Django 6.0.3 on 2026-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalloginchallenge",
            name="magic_token_digest",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hex digest of one-time magic link token (empty for legacy rows).",
                max_length=64,
            ),
        ),
    ]
