# Generated by Django 6.0.3 on 2026-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_portal_login_magic_token_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalIdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_id", models.PositiveIntegerField()),
                ("clinic_id", models.PositiveIntegerField()),
                ("operation", models.CharField(max_length=96)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.SmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client_id", "clinic_id", "-created_at"],
                        name="portal_pid_client_clinic_crt",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client_id", "clinic_id", "operation", "idempotency_key"),
                        name="portal_idem_client_clinic_op_key_uniq",
                    )
                ],
            },
        ),
    ]
