# Generated by Django 6.0.4 on 2026-04-23 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0008_clinic_feature_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("phone_callback", "Oddzwonienie"),
                            ("sign_document", "Do podpisu"),
                            ("check_result", "Sprawdź wynik"),
                            ("other", "Inne"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("patient_name", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Otwarte"),
                            ("in_progress", "W toku"),
                            ("closed", "Zamknięte"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_comment", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_tasks",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_tasks_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_tasks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
