# Generated by Django 6.0 on 2025-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="apartment",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, default="PL", max_length=2),
        ),
        migrations.AddField(
            model_name="client",
            name="house_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="client",
            name="postal_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="client",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
