# Generated by Django 6.0 on 2026-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_apartment_client_city_client_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, default="Polska", max_length=100),
        ),
    ]
