# Generated by Django 6.0.2 on 2026-02-14 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0004_add_visit_type_and_hospital_stay"),
        ("tenancy", "0002_clinicholiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "lab_type",
                    models.CharField(
                        choices=[("in_clinic", "In-Clinic"), ("external", "External")],
                        default="in_clinic",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=512)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for external labs used by multiple clinics",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="tenancy.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "hospital_stay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="scheduling.hospitalstay",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="labs.lab",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="labs.laborder",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                (
                    "value_numeric",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("reference_range", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="labs.laborderline",
                    ),
                ),
            ],
            options={
                "ordering": ["order_line__test__name"],
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("reference_range", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = test available at any lab",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="labs.lab",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="laborderline",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_lines",
                to="labs.labtest",
            ),
        ),
        migrations.AddIndex(
            model_name="lab",
            index=models.Index(fields=["clinic"], name="labs_lab_clinic__e9870d_idx"),
        ),
        migrations.AddIndex(
            model_name="lab",
            index=models.Index(fields=["lab_type"], name="labs_lab_lab_typ_f1a302_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["clinic", "status"], name="labs_labord_clinic__c519e3_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["patient"], name="labs_labord_patient_5a23f2_idx"),
        ),
        migrations.AddIndex(
            model_name="labtest",
            index=models.Index(fields=["lab"], name="labs_labtes_lab_id_ea565d_idx"),
        ),
        migrations.AddIndex(
            model_name="labtest",
            index=models.Index(fields=["code"], name="labs_labtes_code_16a62d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="laborderline",
            unique_together={("order", "test")},
        ),
    ]
