# Generated by Django 6.0.3 on 2026-04-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0017_appointment_booked_via_portal"),
        ("tenancy", "0006_clinic_reminder_sms_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("unmatched", "Unmatched"),
                            ("ambiguous", "Ambiguous"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("vendor_test_code", models.CharField(blank=True, max_length=128)),
                ("vendor_test_name", models.CharField(blank=True, max_length=255)),
                ("value_text", models.CharField(blank=True, max_length=512)),
                (
                    "value_numeric",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=64)),
                ("ref_low", models.CharField(blank=True, max_length=64)),
                ("ref_high", models.CharField(blank=True, max_length=64)),
                ("abnormal_flag", models.CharField(blank=True, max_length=32)),
                (
                    "result_status",
                    models.CharField(
                        blank=True, help_text="e.g. preliminary / final from HL7", max_length=32
                    ),
                ),
                (
                    "natural_key",
                    models.CharField(
                        help_text="Unique within envelope (row index, OBX id, …)", max_length=128
                    ),
                ),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["envelope_id", "natural_key"],
            },
        ),
        migrations.CreateModel(
            name="LabResultComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=512)),
                (
                    "value_numeric",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=64)),
                ("ref_low", models.CharField(blank=True, max_length=64)),
                ("ref_high", models.CharField(blank=True, max_length=64)),
                ("abnormal_flag", models.CharField(blank=True, max_length=32)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "lab_test__name"],
            },
        ),
        migrations.CreateModel(
            name="LabSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "internal_sample_code",
                    models.CharField(
                        help_text="Clinic-issued sample ID printed on label", max_length=128
                    ),
                ),
                ("sample_type", models.CharField(blank=True, max_length=64)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("collected", "Collected"),
                            ("sent", "Sent"),
                            ("rejected", "Rejected"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabTestCodeMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vendor_code", models.CharField(max_length=128)),
                ("vendor_unit", models.CharField(blank=True, max_length=64)),
                ("priority", models.IntegerField(default=0)),
                ("species", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-priority", "vendor_code"],
            },
        ),
        migrations.AddField(
            model_name="laborder",
            name="external_accession_number",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="labresult",
            name="integration_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labresult",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("integration", "Integration"), ("mixed", "Mixed")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="laborder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("in_progress", "In Progress"),
                    ("partial_result", "Partial result"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LabExternalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scheme", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=256)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_external_identifiers",
                        to="tenancy.clinic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabIntegrationDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=128)),
                (
                    "device_model",
                    models.CharField(blank=True, help_text="Analyzer model name", max_length=128),
                ),
                (
                    "connection_kind",
                    models.CharField(
                        choices=[
                            ("hl7_mllp", "HL7 MLLP"),
                            ("hl7_file", "HL7 file"),
                            ("file_drop", "File drop / JSON payload"),
                            ("sql_poll", "SQL poll"),
                            ("rest_webhook", "REST webhook"),
                            ("rest_poll", "REST poll"),
                        ],
                        default="file_drop",
                        max_length=32,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "ingest_token",
                    models.CharField(
                        blank=True,
                        help_text="Shared secret for POST ingest; compare with X-Lab-Ingest-Token header.",
                        max_length=128,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_integration_devices",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_devices",
                        to="labs.lab",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabIngestionEnvelope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=512)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("hl7", "HL7"),
                            ("file", "File"),
                            ("sql", "SQL"),
                            ("api", "API"),
                            ("manual_upload", "Manual upload"),
                        ],
                        default="api",
                        max_length=32,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("mapping", "Mapping"),
                            ("attaching", "Attaching"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                            ("dead_letter", "Dead letter"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                (
                    "raw_file",
                    models.FileField(
                        blank=True, max_length=512, null=True, upload_to="lab_ingestion/%Y/%m/%d/"
                    ),
                ),
                (
                    "raw_body_text",
                    models.TextField(
                        blank=True,
                        help_text="Small payloads (e.g. tests); prefer raw_file for large data in production.",
                    ),
                ),
                ("raw_sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_detail", models.CharField(blank=True, max_length=512)),
                ("payload_metadata", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_ingestion_envelopes",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_envelopes",
                        to="labs.labintegrationdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="laborder",
            name="integration_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_orders",
                to="labs.labintegrationdevice",
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["clinic", "external_accession_number"],
                name="labs_labord_clinic__d4d72a_idx",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_observations",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observations",
                to="labs.labintegrationdevice",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="envelope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="labs.labingestionenvelope",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="internal_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integration_observations",
                to="labs.labtest",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="lab_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_observations",
                to="labs.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="lab_order_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_observations",
                to="labs.laborderline",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="primary_observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="labs.labobservation",
            ),
        ),
        migrations.AddField(
            model_name="labresultcomponent",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_result_components",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="labresultcomponent",
            name="lab_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="labs.labresult",
            ),
        ),
        migrations.AddField(
            model_name="labresultcomponent",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_components",
                to="labs.labtest",
            ),
        ),
        migrations.AddField(
            model_name="labresultcomponent",
            name="source_observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_components",
                to="labs.labobservation",
            ),
        ),
        migrations.AddField(
            model_name="labsample",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_samples",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="labsample",
            name="lab_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="labs.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labobservation",
            name="sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_observations",
                to="labs.labsample",
            ),
        ),
        migrations.AddField(
            model_name="labexternalidentifier",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_ids",
                to="labs.labsample",
            ),
        ),
        migrations.AddField(
            model_name="labtestcodemap",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_test_code_maps",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="labtestcodemap",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_code_maps",
                to="labs.labintegrationdevice",
            ),
        ),
        migrations.AddField(
            model_name="labtestcodemap",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_code_maps",
                to="labs.labtest",
            ),
        ),
        migrations.AddIndex(
            model_name="labintegrationdevice",
            index=models.Index(
                fields=["clinic", "is_active"], name="labs_labint_clinic__796524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labingestionenvelope",
            index=models.Index(
                fields=["clinic", "processing_status"], name="labs_labing_clinic__4685ec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labingestionenvelope",
            constraint=models.UniqueConstraint(
                fields=("clinic", "idempotency_key"),
                name="labs_labingestion_clinic_idempotency_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="labresultcomponent",
            index=models.Index(
                fields=["clinic", "lab_result"], name="labs_labres_clinic__165e0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labresultcomponent",
            constraint=models.UniqueConstraint(
                fields=("lab_result", "lab_test"), name="labs_labrescomp_result_test_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="labsample",
            index=models.Index(fields=["lab_order"], name="labs_labsam_lab_ord_0d5d6b_idx"),
        ),
        migrations.AddConstraint(
            model_name="labsample",
            constraint=models.UniqueConstraint(
                fields=("clinic", "internal_sample_code"),
                name="labs_labsample_clinic_internal_code_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="labobservation",
            index=models.Index(
                fields=["clinic", "match_status"], name="labs_labobs_clinic__c89985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labobservation",
            index=models.Index(fields=["lab_order"], name="labs_labobs_lab_ord_12d6b0_idx"),
        ),
        migrations.AddConstraint(
            model_name="labobservation",
            constraint=models.UniqueConstraint(
                fields=("envelope", "natural_key"), name="labs_labobs_envelope_natural_key_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="labexternalidentifier",
            index=models.Index(fields=["clinic", "scheme"], name="labs_labext_clinic__ff9f5f_idx"),
        ),
        migrations.AddConstraint(
            model_name="labexternalidentifier",
            constraint=models.UniqueConstraint(
                fields=("clinic", "scheme", "value"), name="labs_labextid_clinic_scheme_value_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="labtestcodemap",
            index=models.Index(
                fields=["clinic", "vendor_code"], name="labs_labtes_clinic__e976ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtestcodemap",
            index=models.Index(
                fields=["device", "vendor_code"], name="labs_labtes_device__c1e868_idx"
            ),
        ),
    ]
