# Generated by Django 6.0.3 on 2026-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_lab_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="labingestionenvelope",
            name="raw_s3_bucket",
            field=models.CharField(
                blank=True,
                help_text="When set with raw_s3_key, raw bytes are loaded from S3 for parsing/reprocess.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="labingestionenvelope",
            name="raw_s3_key",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
