# Generated by Django 6.0

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_add_user_role"),
        ("labs", "0001_initial"),
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0009_remove_time_from_working_hours_unique"),
        ("tenancy", "0003_clinic_nip_ksef_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("treatment_history", "Treatment history"),
                            ("lab_outcome", "Lab outcome"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual upload"),
                            ("api_ingest", "API ingest"),
                        ],
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("original_filename", models.CharField(max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("input_s3_key", models.CharField(blank=True, max_length=1024)),
                ("output_html_s3_key", models.CharField(blank=True, max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_documents",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_documents",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_documents",
                        to="labs.laborder",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_ingestion_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestiondocument",
            index=models.Index(
                fields=["clinic", "status"],
                name="documents_i_clinic__e2e0a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestiondocument",
            index=models.Index(
                fields=["clinic", "patient", "-created_at"],
                name="documents_i_clinic__a8b0f6_idx",
            ),
        ),
    ]
