# Generated by Django 6.0 on 2026-03-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ingestiondocument",
            new_name="documents_i_clinic__a515cc_idx",
            old_name="documents_i_clinic__e2e0a4_idx",
        ),
        migrations.RenameIndex(
            model_name="ingestiondocument",
            new_name="documents_i_clinic__01945f_idx",
            old_name="documents_i_clinic__a8b0f6_idx",
        ),
    ]
