# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_rename_documents_i_clinic__e2e0a4_idx_documents_i_clinic__a515cc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestiondocument",
            name="last_error",
            field=models.TextField(blank=True),
        ),
    ]
