# Generated by Django 6.0.3 on 2026-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportexportjob",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("revenue_summary", "Revenue Summary"),
                    ("reminder_analytics", "Reminder Analytics"),
                    ("cancellation_analytics", "Cancellation Analytics"),
                    ("accounting_invoice_lines", "Accounting invoice lines (CSV)"),
                ],
                max_length=64,
            ),
        ),
    ]
