# Generated by Django 6.0.2 on 2026-02-14 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0003_vetavailabilityexception"),
        ("tenancy", "0002_clinicholiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="visit_type",
            field=models.CharField(
                choices=[("outpatient", "Outpatient"), ("hospitalization", "Hospitalization")],
                default="outpatient",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HospitalStay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("admitted", "Admitted"), ("discharged", "Discharged")],
                        default="admitted",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("cage_or_room", models.CharField(blank=True, max_length=64)),
                ("admitted_at", models.DateTimeField()),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                ("discharge_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_stays",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "attending_vet",
                    models.ForeignKey(
                        limit_choices_to={"is_vet": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hospital_stays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hospital_stays",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hospital_stays",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-admitted_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status"], name="scheduling__clinic__f13d43_idx"
                    ),
                    models.Index(
                        fields=["patient", "admitted_at"], name="scheduling__patient_80de73_idx"
                    ),
                ],
            },
        ),
    ]
