# Generated by Django 6.0 on 2026-02-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_add_visit_type_and_hospital_stay'),
        ('tenancy', '0002_clinicholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in lists (lower first)')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenancy.clinic')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.room'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='scheduling_room_clinic_name_uniq'),
        ),
    ]
