# Generated by Django 6.0 on 2026-03-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0005_add_room_and_appointment_room"),
        ("tenancy", "0002_clinicholiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingQueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chief_complaint", models.CharField(blank=True, max_length=255)),
                ("is_urgent", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("left", "Left"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("arrived_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_entry",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "called_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="called_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_entries",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "arrived_at"],
            },
        ),
    ]
