# Generated by Django 6.0.2 on 2026-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_add_clinic_working_hours_and_duty_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicworkinghours",
            name="shift_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Duty shift length in hours. Leave blank for a single shift covering the full open period.",
                null=True,
            ),
        ),
    ]
