# Generated by Django 6.0.2 on 2026-03-17 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_add_shift_hours_to_clinic_working_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vetworkinghours",
            unique_together={("vet", "weekday")},
        ),
    ]
