# Generated by Django 6.0

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0009_remove_time_from_working_hours_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("original_filename", models.CharField(max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("input_s3_key", models.CharField(blank=True, max_length=1024)),
                ("transcript", models.TextField(blank=True)),
                ("summary_text", models.TextField(blank=True)),
                ("summary_structured", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_recordings",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_recordings",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_visit_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="visitrecording",
            index=models.Index(
                fields=["clinic", "status"],
                name="scheduling_v_clinic__7d9698_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitrecording",
            index=models.Index(
                fields=["appointment", "-created_at"],
                name="scheduling_v_appoint_537f65_idx",
            ),
        ),
    ]
