# Generated by Django 6.0 on 2026-03-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0010_visitrecording"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="visitrecording",
            new_name="scheduling__clinic__49235b_idx",
            old_name="scheduling_v_clinic__7d9698_idx",
        ),
        migrations.RenameIndex(
            model_name="visitrecording",
            new_name="scheduling__appoint_1f6f86_idx",
            old_name="scheduling_v_appoint_537f65_idx",
        ),
    ]
