# Generated by Django 6.0.3 on 2026-03-30 20:01

from django.conf import settings
from django.db import migrations, models


def backfill_booked_via_portal(apps, schema_editor):
    AuditLog = apps.get_model("audit", "AuditLog")
    Appointment = apps.get_model("scheduling", "Appointment")
    for log in AuditLog.objects.filter(
        action="portal_appointment_booked",
        entity_type="appointment",
    ).iterator():
        try:
            appt_id = int(log.entity_id)
        except (TypeError, ValueError):
            continue
        Appointment.objects.filter(pk=appt_id, clinic_id=log.clinic_id).update(
            booked_via_portal=True
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("billing", "0003_ksef_fields"),
        ("patients", "0002_add_ai_summary_cache"),
        ("scheduling", "0016_appointment_portal_deposit_invoice"),
        ("tenancy", "0005_clinic_portal_booking_deposit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="booked_via_portal",
            field=models.BooleanField(
                default=False,
                help_text="True when the visit was created through the owner booking portal.",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clinic", "booked_via_portal", "starts_at"],
                name="sch_appt_clinic_bvp_start",
            ),
        ),
        migrations.RunPython(backfill_booked_via_portal, noop_reverse),
    ]
