# Generated by Django 6.0.3 on 2026-04-04 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0017_appointment_booked_via_portal"),
        ("tenancy", "0007_clinic_network"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitTranscriptionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="visit_transcriptions/%Y/%m/%d/",
                    ),
                ),
                ("original_filename", models.CharField(max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField()),
                ("transcript", models.TextField(blank=True)),
                ("structured", models.JSONField(blank=True, default=dict)),
                ("needs_review", models.BooleanField(blank=True, null=True)),
                ("unknown_fields", models.JSONField(blank=True, default=list)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_transcription_jobs",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_transcription_jobs",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_transcription_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status"], name="scheduling__clinic__71067d_idx"
                    ),
                    models.Index(
                        fields=["appointment", "-created_at"], name="scheduling__appoint_98c113_idx"
                    ),
                ],
            },
        ),
    ]
