# Generated by Django 6.0 on 2026-04-24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0008_clinic_feature_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("node_id", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("version", models.CharField(blank=True, max_length=64)),
                ("host", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("degraded", "Degraded"),
                        ],
                        default="online",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_agents",
                        to="tenancy.clinic",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(choices=[("lab", "Lab"), ("fiscal", "Fiscal")], max_length=16),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("offline", "Offline"),
                        ],
                        default="discovered",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                ("connection_type", models.CharField(blank=True, max_length=32)),
                ("connection_config", models.JSONField(blank=True, default=dict)),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        help_text="Agent-reported stable reference for upsert matching.",
                        max_length=128,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="tenancy.clinic",
                    ),
                ),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("command_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acked", "Acked"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.CharField(blank=True, max_length=512)),
                (
                    "idempotency_key",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="device_management.agentnode",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_commands",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="device_management.device",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("message", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="device_management.agentnode",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_events",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="device_management.device",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DeviceHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heartbeats",
                        to="device_management.agentnode",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_heartbeats",
                        to="tenancy.clinic",
                    ),
                ),
            ],
            options={"ordering": ["-received_at"]},
        ),
        migrations.CreateModel(
            name="DeviceCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="device_management.device",
                    ),
                ),
            ],
            options={"ordering": ["code", "id"]},
        ),
        migrations.CreateModel(
            name="FiscalReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sale_ref", models.CharField(blank=True, max_length=128)),
                ("buyer_tax_id", models.CharField(blank=True, max_length=32)),
                ("gross_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="PLN", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent_to_agent", "Sent to agent"),
                            ("printed", "Printed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fiscal_number", models.CharField(blank=True, max_length=128)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_receipts",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        limit_choices_to={"device_type": "fiscal"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_receipts",
                        to="device_management.device",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="FiscalReceiptPrintAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_no", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acked", "Acked"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_attempts",
                        to="device_management.devicecommand",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="device_management.fiscalreceipt",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="agentnode",
            constraint=models.UniqueConstraint(
                fields=("clinic", "node_id"), name="device_management_agent_clinic_node_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["clinic", "device_type"], name="device_manag_clinic__568040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["clinic", "lifecycle_state"], name="device_manag_clinic__293588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["external_ref"], name="device_manag_externa_536fce_idx"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref__gt", "")),
                fields=("clinic", "external_ref"),
                name="device_management_device_clinic_external_ref_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["clinic", "status", "created_at"], name="device_manag_clinic__dd565d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceevent",
            index=models.Index(
                fields=["clinic", "severity", "created_at"], name="device_manag_clinic__7f9937_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceheartbeat",
            index=models.Index(
                fields=["clinic", "received_at"], name="device_manag_clinic__f97f0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicecapability",
            constraint=models.UniqueConstraint(
                fields=("device", "code"),
                name="device_management_capability_device_code_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalreceipt",
            index=models.Index(
                fields=["clinic", "status", "created_at"], name="device_manag_clinic__542747_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalreceiptprintattempt",
            constraint=models.UniqueConstraint(
                fields=("receipt", "attempt_no"),
                name="device_management_fiscal_attempt_receipt_no_uniq",
            ),
        ),
    ]
